module.exports = {
    requestFailed: 'Something went wrong, Please try again later',
    registered: 'User has been registered with us',
    wrongPassword: { description: 'That’s an incorrect password. Please try again.', code: 1902 },
    invalidEmail: { description: 'Please provide a valid email', code: 1904 },
    invalidUid: { description: 'Please provide a valid UID', code: 1905 },
    invalidAccessToken: { description: 'Invalid token', code: 1899 },
    InvalidExpiredKalturaSession: 'Invalid or expired Kaltura Session.',
    userDoesNotExist: { description: 'User does not exist', code: 1903 },
    kalturaUserDoesNotExist: { description: 'Kaltura user does not exist', code: 1917 },
    kalturaUserWrongUsernameOrPassword: { description: 'Kaltura Exception - wrong username or password', code: 1918 },
    kalturaInsideLockTime: { description: 'Kaltura Exception - Too many unsuccessful login attempts.', code: 1919 },
    userDoesExist: 'User does exist.',
    profileDoesNotExist: 'Profile does not exist.',
    profileDeleteSuccess: 'Profile has been deleted successfully.',
    profileCreationLimit: 'Exceeded max profile creation limit.',
    emailNotRegistered: { description: 'This email is not registered with us', code: 1908 },
    emailAlreadyRegistered: { description: 'This Email is already registered with us', code: 1901 },
    requiredResetPassword: 'Please reset your password.',
    checkEmailSocialLogin: { description: 'Please try to login with your social account.', code: 400 },
    otpDataNotFound: { description: 'Please initiate an OTP request first.', code: 1923 },
    otpVerificationFailed: { description: 'Please enter the correct OTP', code: 1924 },
    otpExpired: { description: 'OTP expired.', code: 1925 },
    mobileAlreadyExist: { description: 'User alredy exist with this mobile number.', code: 1926 },
    otpLimitExceeded: { description: 'OTP generation limit exceeded.', code: 1927 },
    mobileNotRegistered: { description: 'This mobile number is not registered with us', code: 1928 },
    invalidFborGToken: { description: 'Invalid auth credentials token', code: 1907 },
    invalidTncVersion: { description: 'Please provide a valid tncVersion', code: 1826 },
    invalidTncAcceptTime: { description: 'Please provide a valid tncAcceptTime', code: 1827 },
    expiredIdToken: { description: 'The Id token has been expired', code: 1933 },
    invalidNonce: { description: 'The Nonce is not valid', code: 1934 },
    invalidIdToken: { description: 'The ID token or AuthCode is not valid', code: 1935 },
    emailOtpSuccessMsg: 'OTP sent to your email address, Please verify it.',
    mobileNotVerify: { description: 'Mobile number is not verify, Please verify it', code: 1930 },

    expiredToken: { description: 'The token has been expired.', code: 1898 },
    expiredRefreshToken: { description: 'The token has been expired.', code: 1929 },
    invalidProfileToken: { description: 'Invalid token', code: 1899 },
    typeMissing: { description: 'No Valid Provider type given', code: 1803 },
    validationError: {
        username: '1801',
        password: '1802',
        firstName: '1803',
        lastName: '1804',
        username: '1805', 
        limit: '1806',
        productId: '1807',
        name: '1808',
        sku: '1809',
        price: '1810'
    }
};